### PR TITLE
Add Zope to the readme.

### PR DESCRIPTION
**Pull request by mauritsvanrees**

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jugmac00 can you review this?

**Comment by jugmac00** [comment]
While I cannot assign myself as reviewer - maybe I am not part in the proper team (of 18!!), I can certainly review the PR from the file view - which I will do next week, when it is a bit slower at work.

A final decision should be made by @icemac or Jens V., as they are part of the security team.

From a user's perspective, and unfortunately only from a quick glance, I like your proposal very much!

Thanks for all!

**Review by icemac — APPROVED** [review]
LGTM.

**Comment by icemac** [comment]
Hm, my approval does not seem to count.
Ah, I have no write access, that's why.

**Comment by mauritsvanrees** [comment]
I have merged it myself (as admin I can override that a review is required).
I have given the plone / developers team write access now.

**Comment by mauritsvanrees** [comment]
I have added the information on plone.org as well:

- [official hotfix page](https://plone.org/security/hotfix/20210518)
- [original announcement of hotfix release](https://plone.org/security/announcements/security-patch-released-20210518)
- [pre announcement](https://plone.org/security/announcements/20210518-preannounce). Here I kept the text very general: "Zope is also affected. A new version of Zope, or a related package, will be available around the time of the hotfix. If you cannot upgrade to this new version, you can try the Plone hotfix on your Zope site."
- [announcement of hotfix version 1.4](https://plone.org/news/security-patch-20210518-version-1-4-released): "Zope users are advised to upgrade to Zope 4.6.1 or 5.2.1. If this is not possible, you can try this new version of the hotfix."

**Pull request merged**
